import {DT,SHAPES,clamp,target,localInputs,inTrainingRange,LearnedDynamics,pickParticleDepth} from './core.js';
import {ParticleEngine} from './engine.js';
const $=s=>document.querySelector(s), root=document.documentElement;
let engine,canvas=$('#particles'),model=null,paused=false,phase=0,tool='push',yaw=.48,pitch=.3,pan=[0,0],held=false,dragging=false,lastPointer=[0,0],mouse={x:0,y:0,inside:false},messageTimer;
let samples=[],history=[],last=performance.now(),startTime=last,accum=0,lastSample=last,lastCompare=0,lastLog=0,latestError=null,latestPredictionMs=null,frameAverage=16.67,configuredCount=6000;
let diagnosticReadMs=0,resetReason='startup';
let autoDepth=null,lastDepthPick=-Infinity,depthPickMs=0;
function message(text){$('#message').textContent=text;$('#message').hidden=false;clearTimeout(messageTimer);messageTimer=setTimeout(()=>$('#message').hidden=true,5500);}
function read(key){return +$('#'+key).value;}
function camera(){const c=Math.cos(yaw),s=Math.sin(yaw),ct=Math.cos(pitch),st=Math.sin(pitch);return[c,st*s,-ct*s,0,ct,st,s,-st*c,ct*c];}
function params(){const r=canvas.getBoundingClientRect(),m=camera(),zoom=read('zoom')/100,unit=Math.max(1,Math.min(r.width,r.height)*.36*zoom),x=(mouse.x-r.width/2-pan[0])/unit,y=(r.height/2-mouse.y-pan[1])/unit,z=$('#depth-mode').value==='auto'?(autoDepth??0):read('depth')/100*1.2,hasDepth=$('#depth-mode').value!=='auto'||autoDepth!==null;return{shape:read('shape'),phase,push:[m[0]*x+m[1]*y+m[2]*z,m[3]*x+m[4]*y+m[5]*z,m[6]*x+m[7]*y+m[8]*z],radius:clamp((14+read('radius')*.45)/unit,.05,.75),strength:read('strength')*.18,recovery:read('recovery'),toolVisible:tool==='push'&&mouse.inside&&hasDepth,pushing:tool==='push'&&held&&mouse.inside&&hasDepth,moving:$('#moving').checked,camera:m,pan,zoom,pointSize:read('size')};}
function depthLabels(){
 const automatic=$('#depth-mode').value==='auto';$('#depth').disabled=automatic;
 $('#depth-note').textContent=automatic?(autoDepth===null?'Point at particles to set depth. Empty space does not push.':'Following the frontmost particles under the cursor.'):'Choose how far into the scene to push.';
 if(automatic)$('#depth-out').textContent=autoDepth===null?'No target':(autoDepth<0?'Near ':'Far ')+Math.abs(autoDepth).toFixed(2);
}
function updateAutoDepth(now){
 depthPickMs=0;
 if($('#depth-mode').value!=='auto')return;
 if(tool!=='push'||!mouse.inside){autoDepth=null;depthLabels();return;}
 if(now-lastDepthPick<100)return;
 const start=performance.now(),r=canvas.getBoundingClientRect(),p=params();
 const unit=Math.max(1,Math.min(r.width,r.height)*.36*p.zoom);
 const x=(mouse.x-r.width/2-pan[0])/unit,y=(r.height/2-mouse.y-pan[1])/unit;
 autoDepth=pickParticleDepth(engine.seeds,engine.sample(engine.count),engine.count,p.shape,phase,p.camera,x,y,10/unit);
 lastDepthPick=now;depthPickMs=performance.now()-start;depthLabels();
}
function labels(){for(const [id,value]of Object.entries({speed:read('speed').toFixed(1)+'×',radius:read('radius')+'%',strength:read('strength')+'%',depth:read('depth')===0?'Center':(read('depth')<0?'Near ':'Far ')+Math.abs(read('depth'))+'%',recovery:read('recovery'),zoom:read('zoom')+'%',size:read('size').toFixed(1)+' px'}))$('#'+id+'-out').textContent=value;const shape=read('shape');$('#scene-title').textContent=SHAPES[shape][0].toUpperCase()+SHAPES[shape].slice(1);$('#scene-subtitle').textContent=configuredCount.toLocaleString()+' particles · '+(paused?'paused':$('#moving').checked?'moving':'shape held');$('#motion-description').textContent=['Particles travel along the sphere surface.','Particles move freely along reflected paths inside the cube.','Particles circulate around the ring.','Particles travel up and down the helix.'][shape];depthLabels();}
function freshCanvas(){const next=document.createElement('canvas');next.id='particles';next.setAttribute('role','img');next.setAttribute('aria-label','Interactive three dimensional particles');canvas.replaceWith(next);canvas=next;bindCanvas();}
function initEngine(forceCPU=false){if(engine)engine.dispose();freshCanvas();try{engine=new ParticleEngine(canvas,{forceCPU});}catch(err){console.warn('Graphics mode unavailable:',err.message);freshCanvas();engine=new ParticleEngine(canvas,{forceCPU:true});message('Graphics mode unavailable. Running the CPU reference.');}if(engine.isCPU){$('#backend').value='cpu';$('#count').max='10000';$('#backend-note').textContent='CPU calculations and drawing. Maximum 10,000 particles.';}else{$('#backend').value='gpu';$('#count').max='50000';$('#backend-note').textContent='Graphics-buffer compute. Hardware acceleration depends on your browser.';}$('#mode-label').textContent=engine.label.toUpperCase();$('#submit-label').textContent=engine.isCPU?'CPU simulation ms / frame':'CPU submission ms / frame';$('#gpu-caption').textContent=engine.isCPU?'Not applicable':engine.timer?'Measured asynchronously':'Unavailable in this browser';engine.resize();reset('compute mode');}
function reset(reason='reset'){const limit=engine.isCPU?10000:50000;let n=read('count'),seed=read('seed');if(!Number.isFinite(n)||n<300||n>limit){n=clamp(Number.isFinite(n)?Math.round(n):6000,300,limit);message('Particle count adjusted to the supported range.');}if(!Number.isInteger(seed)||seed<1||seed>2147483647){seed=731;$('#seed').value=seed;}configuredCount=Math.round(n);$('#count').value=configuredCount;engine.configure(configuredCount,seed);phase=0;accum=0;autoDepth=null;lastDepthPick=-Infinity;samples=[];startTime=performance.now();lastCompare=0;latestError=null;resetReason=reason;$('#live-error').textContent='—';labels();}
function settings(){return{version:1,shape:read('shape'),count:configuredCount,seed:read('seed'),moving:$('#moving').checked,speed:read('speed'),radius:read('radius'),strength:read('strength'),depth:read('depth'),depthMode:$('#depth-mode').value,recovery:read('recovery'),zoom:read('zoom'),size:read('size'),yaw,pitch,pan:[...pan],backend:$('#backend').value};}
function loadSettings(s){if(!s||s.version!==1)throw Error('Unsupported setup format');const ranges={shape:[0,3],count:[300,50000],seed:[1,2147483647],speed:[.1,2],radius:[0,100],strength:[10,100],depth:[-100,100],recovery:[3,14],zoom:[50,160],size:[1,5]};for(const [key,[lo,hi]]of Object.entries(ranges)){if(typeof s[key]!=='number'||!Number.isFinite(s[key])||s[key]<lo||s[key]>hi)throw Error('Invalid setting: '+key);if(['shape','count','seed'].includes(key)&&!Number.isInteger(s[key]))throw Error('Expected a whole number for '+key);}if(s.depthMode!==undefined&&!['manual','auto'].includes(s.depthMode))throw Error('Invalid depth mode');if(typeof s.moving!=='boolean')throw Error('Invalid motion setting');if(s.backend!==undefined&&!['gpu','cpu'].includes(s.backend))throw Error('Invalid compute mode');for(const key of Object.keys(ranges))$('#'+key).value=s[key];$('#moving').checked=s.moving;$('#depth-mode').value=s.depthMode??'manual';yaw=Number.isFinite(s.yaw)?clamp(s.yaw,-Math.PI*20,Math.PI*20):.48;pitch=Number.isFinite(s.pitch)?clamp(s.pitch,-1.4,1.4):.3;pan=Array.isArray(s.pan)&&s.pan.length===2&&s.pan.every(Number.isFinite)?s.pan.map(v=>clamp(v,-1000,1000)):[0,0];if(s.backend&&s.backend!==$('#backend').value)initEngine(s.backend==='cpu');else reset('loaded setup');}
function download(name,data,mime){const blob=data instanceof Blob?data:new Blob([data],{type:mime});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function stamp(){return new Date().toISOString().replace(/[:.]/g,'-');}
function saveLocal(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{message('Browser storage unavailable; file exports still work.');}}
function readLocal(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function setPaused(value){paused=value;$('#pause').textContent=paused?'Resume':'Pause';$('#pause').setAttribute('aria-pressed',String(paused));held=false;accum=0;last=performance.now();labels();}
function bindCanvas(){canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;setPointer(e);lastDepthPick=-Infinity;held=true;dragging=true;lastPointer=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{setPointer(e);if(dragging){const dx=e.clientX-lastPointer[0],dy=e.clientY-lastPointer[1];if(tool==='orbit'){yaw+=dx*.006;pitch=clamp(pitch+dy*.006,-1.4,1.4);}if(tool==='pan'){pan[0]+=dx;pan[1]-=dy;}}lastPointer=[e.clientX,e.clientY];});const release=e=>{held=false;dragging=false;if(e&&canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('lostpointercapture',()=>{held=false;dragging=false;});canvas.addEventListener('pointerleave',()=>{if(!dragging)mouse.inside=false;});canvas.addEventListener('wheel',e=>{e.preventDefault();$('#zoom').value=clamp(read('zoom')-Math.sign(e.deltaY)*5,50,160);labels();},{passive:false});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();setPaused(true);message('Graphics context interrupted. Switch to CPU reference or reload.');});canvas.addEventListener('webglcontextrestored',()=>{initEngine(false);message('Graphics restored; formation reset.');});}
function setPointer(e){const r=canvas.getBoundingClientRect();if(Math.hypot(e.clientX-r.left-mouse.x,e.clientY-r.top-mouse.y)>6)autoDepth=null;mouse.x=e.clientX-r.left;mouse.y=e.clientY-r.top;mouse.inside=mouse.x>=0&&mouse.y>=0&&mouse.x<r.width&&mouse.y<r.height;}
const overlay=$('#overlay'),oc=overlay.getContext('2d');
function drawOverlay(p){const r=canvas.getBoundingClientRect(),dpr=engine.dpr||1;const w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(overlay.width!==w||overlay.height!==h){overlay.width=w;overlay.height=h;}oc.setTransform(dpr,0,0,dpr,0,0);oc.clearRect(0,0,r.width,r.height);if(!p.toolVisible)return;const radius=p.radius*Math.min(r.width,r.height)*.36*p.zoom;oc.strokeStyle=held?'rgba(255,255,255,.65)':'rgba(255,255,255,.3)';oc.lineWidth=1;oc.beginPath();oc.arc(mouse.x,mouse.y,radius,0,Math.PI*2);oc.stroke();oc.beginPath();oc.ellipse(mouse.x,mouse.y,radius,radius*.3,0,0,Math.PI*2);oc.stroke();oc.fillStyle='#fff';oc.beginPath();oc.arc(mouse.x,mouse.y,2,0,Math.PI*2);oc.fill();}
async function loadModel(){try{const res=await fetch('models/dynamics.json');if(!res.ok)throw Error('Model file unavailable');model=new LearnedDynamics(await res.json());const d=model.data;$('#model-name').textContent=d.model;$('#model-summary').textContent='Bundled trained model · '+d.epochs+' epochs · held-out quality checks passed';$('#test-error').textContent=d.held_out_test.velocity_rmse.toFixed(5)+' units/s';$('#training-count').textContent=d.training_samples.toLocaleString();}catch(err){$('#model-name').textContent='Comparison unavailable';$('#model-summary').textContent='The model could not load. Particle motion remains available.';$('#ai-enabled').checked=false;$('#ai-enabled').disabled=true;console.warn(err.message);}}
function beforeComparison(p){const t0=performance.now(),state=engine.sample(64);diagnosticReadMs=performance.now()-t0;const records=[],start=performance.now();for(let i=0;i<state.length/6;i++){const off=Array.from(state.subarray(i*6,i*6+3)),vel=Array.from(state.subarray(i*6+3,i*6+6)),base=target(engine.seeds.subarray(i*4,i*4+4),p.shape,p.phase),input=localInputs(base,off,vel,p);if(inTrainingRange(input)){const predicted=model.predict(input);if(predicted.offset.every(Number.isFinite))records.push({i,predicted,input});}}latestPredictionMs=performance.now()-start;return records;}
function afterComparison(records,now){const t=performance.now(),after=engine.sample(64);diagnosticReadMs+=performance.now()-t;if(!records.length){$('#live-error').textContent='Outside training range';return;}let sum=0;for(const r of records)for(let k=0;k<3;k++)sum+=(r.predicted.offset[k]-after[r.i*6+k])**2;latestError=Math.sqrt(sum/(records.length*3));$('#live-error').textContent=latestError.toExponential(2)+' units';$('#prediction-time').textContent=latestPredictionMs.toFixed(2)+' ms / '+records.length+' particles';if(now-lastLog>1800){lastLog=now;const log=$('#comparison-log');if(log.querySelector('p'))log.textContent='';const row=document.createElement('div');row.className='log-entry';row.textContent=new Date().toLocaleTimeString()+' · '+records.length+'/64 sampled · RMSE '+latestError.toExponential(2);log.prepend(row);while(log.children.length>5)log.lastElementChild.remove();}}
const chart=$('#performance-chart'),cc=chart.getContext('2d');let chartHover=null,chartBounds=null;
function drawChart(){const r=chart.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=r.width,h=r.height;chart.width=Math.max(1,Math.round(w*dpr));chart.height=Math.max(1,Math.round(h*dpr));cc.setTransform(dpr,0,0,dpr,0,0);cc.clearRect(0,0,w,h);const left=w<260?36:49,right=14,top=18,bottom=31,pw=Math.max(1,w-left-right),ph=Math.max(1,h-top-bottom);let series=[['frame_ms','Frame interval','#ededed',$('#show-frame').checked],['submission_ms','Simulation work','#8cd4ff',$('#show-submit').checked],['gpu_ms','GPU compute + draw','#86eda7',$('#show-gpu').checked]];let vals=[];for(const s of samples)for(const [key,,,on]of series)if(on&&s[key]!==null&&Number.isFinite(s[key]))vals.push(s[key]);const max=Math.max(5,...vals)*1.15,tmax=samples.length?samples[samples.length-1].elapsed_s:0,tmin=Math.max(0,tmax-60),span=Math.max(5,tmax-tmin);chartBounds={left,top,pw,ph,tmin,span,w,h};cc.font='11px Segoe UI,Arial';cc.fillStyle='#aaa';cc.fillText('ms',8,13);cc.strokeStyle='#343434';cc.lineWidth=1;for(let i=0;i<=4;i++){const y=top+ph-i*ph/4;cc.beginPath();cc.moveTo(left,y);cc.lineTo(w-right,y);cc.stroke();cc.textAlign='right';cc.fillText((max*i/4).toFixed(max>20?0:1),left-7,y+4);}const ticks=w<350?2:4;for(let i=0;i<=ticks;i++){const x=left+pw*i/ticks;cc.textAlign=i===0?'left':i===ticks?'right':'center';cc.fillText((tmin+span*i/ticks).toFixed(0)+' s',x,h-9);}cc.save();cc.beginPath();cc.rect(left,top,pw,ph);cc.clip();for(const [key,,color,on]of series){if(!on)continue;cc.strokeStyle=color;cc.lineWidth=1.5;cc.beginPath();let started=false;for(const s of samples){if(s.elapsed_s<tmin)continue;if(s[key]===null||!Number.isFinite(s[key])){started=false;continue;}const x=left+(s.elapsed_s-tmin)/span*pw,y=top+ph-s[key]/max*ph;if(!started){cc.moveTo(x,y);started=true;}else cc.lineTo(x,y);}cc.stroke();}if(chartHover!==null){cc.strokeStyle='#777';cc.lineWidth=1;cc.beginPath();cc.moveTo(chartHover,top);cc.lineTo(chartHover,top+ph);cc.stroke();}cc.restore();if(!samples.length){cc.fillStyle='#aaa';cc.textAlign='center';cc.fillText('Collecting measured timings…',left+pw/2,top+ph/2);}}
chart.addEventListener('pointermove',e=>{if(!chartBounds||!samples.length)return;const r=chart.getBoundingClientRect(),b=chartBounds;chartHover=clamp(e.clientX-r.left,b.left,b.left+b.pw);let t=b.tmin+(chartHover-b.left)/b.pw*b.span,s=samples.reduce((a,v)=>Math.abs(v.elapsed_s-t)<Math.abs(a.elapsed_s-t)?v:a);const tip=$('#chart-tooltip');tip.textContent=`${s.elapsed_s.toFixed(1)} s\nFrame: ${s.frame_ms.toFixed(2)} ms\nSimulation: ${s.submission_ms.toFixed(2)} ms\nGPU: ${s.gpu_ms===null?'unavailable':s.gpu_ms.toFixed(2)+' ms'}`;tip.hidden=false;tip.style.left=Math.max(0,Math.min(chartHover+10,b.w-180))+'px';tip.style.top='14px';drawChart();});chart.addEventListener('pointerleave',()=>{chartHover=null;$('#chart-tooltip').hidden=true;drawChart();});
function recordSample(now,submit,steps){const gpu=engine.gl&&engine.gpuMs!==null&&now-engine.lastGpuAt<1500?engine.gpuMs:null;const row={elapsed_s:(now-startTime)/1000,frame_ms:frameAverage,submission_ms:submit,gpu_ms:gpu,fps:1000/frameAverage,particle_count:configuredCount,shape:SHAPES[read('shape')],backend:engine.label,steps,phase,moving:$('#moving').checked,paused,speed:read('speed'),radius_percent:read('radius'),strength_percent:read('strength'),recovery:read('recovery'),seed:read('seed'),diagnostic_read_ms:diagnosticReadMs,depth_mode:$('#depth-mode').value,depth_pick_ms:depthPickMs,model_position_rmse:latestError};samples.push(row);while(samples.length>650||samples[0].elapsed_s<row.elapsed_s-60)samples.shift();$('#fps-value').textContent=row.fps.toFixed(0);$('#submit-value').textContent=submit.toFixed(2);$('#gpu-value').textContent=gpu===null?'—':gpu.toFixed(2);$('#memory-value').textContent=(engine.allocatedBytes()/1e6).toFixed(2);drawChart();}
function frame(now){try{if(document.hidden){last=now;accum=0;requestAnimationFrame(frame);return;}const raw=(now-last)/1000;last=now;frameAverage=frameAverage*.9+Math.max(1,raw*1000)*.1;const elapsed=Math.min(raw,.05);if(!paused)accum+=elapsed;else accum=0;const steps=Math.min(3,Math.floor(accum/DT));let submission=0;const compare=model&&$('#ai-enabled').checked&&!paused&&steps>0&&now-lastCompare>=500;let capture=null;
 updateAutoDepth(now);
 // Sample before the update. GPU queries deliberately exclude diagnostic reads.
 if(compare){const p=params();if(p.moving)p.phase+=DT*read('speed');capture=beforeComparison(p);lastCompare=now;}
 if(!compare)engine.beginTimer();for(let i=0;i<steps;i++){if($('#moving').checked)phase+=DT*read('speed');let p=params(),t=performance.now();engine.step(p);submission+=performance.now()-t;accum-=DT;if(i===0&&capture){afterComparison(capture,now);capture=null;}}
 let p=params();engine.draw(p);engine.endTimer();engine.pollTimer();drawOverlay(p);if(now-lastSample>=100){lastSample=now;recordSample(now,submission,steps);}if(accum>DT*3)accum=0;
 }catch(err){console.error(err);setPaused(true);message('Simulation stopped safely. Try Reset or CPU reference.');}
 requestAnimationFrame(frame);}
function bindDividers(){let layout=readLocal('particle-lab-layout',null);if(layout&&Number.isFinite(layout.side)&&Number.isFinite(layout.view)){root.style.setProperty('--side',clamp(layout.side,128,400)+'px');root.style.setProperty('--view',clamp(layout.view,180,Math.max(180,innerHeight-180))+'px');}
 for(const [id,vertical]of [['v-divider',true],['h-divider',false]]){const el=$('#'+id);let dragging=false,origin,size;function set(value){if(vertical)root.style.setProperty('--side',clamp(value,Math.min(128,innerWidth*.4),Math.min(400,innerWidth*.4))+'px');else root.style.setProperty('--view',clamp(value,Math.min(180,innerHeight*.5),Math.max(180,innerHeight-165))+'px');}function save(){saveLocal('particle-lab-layout',{side:$('#controls').clientWidth,view:$('#viewport').clientHeight});}el.addEventListener('pointerdown',e=>{e.preventDefault();el.focus();dragging=true;origin=vertical?e.clientX:e.clientY;size=vertical?$('#controls').clientWidth:$('#viewport').clientHeight;el.setPointerCapture(e.pointerId);});el.addEventListener('pointermove',e=>{if(dragging)set(size+(vertical?e.clientX:e.clientY)-origin);});for(const type of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(type,()=>{if(dragging){dragging=false;save();}});el.addEventListener('keydown',e=>{const d=vertical?{ArrowLeft:-15,ArrowRight:15}[e.key]:{ArrowUp:-15,ArrowDown:15}[e.key];if(d){e.preventDefault();set((vertical?$('#controls').clientWidth:$('#viewport').clientHeight)+d);save();}});}}
function drawHistory(){const host=$('#history');host.textContent='';if(!history.length){const p=document.createElement('p');p.className='muted';p.textContent='No saved snapshots yet.';host.append(p);return;}for(const run of history){const row=document.createElement('div');row.className='history-item';const description=document.createElement('div');description.textContent=SHAPES[run.setup.shape]+' · '+run.setup.count.toLocaleString()+' particles';const small=document.createElement('small');small.textContent=run.date+' · '+run.mode+' · '+run.fps.toFixed(0)+' FPS';description.append(small);const button=document.createElement('button');button.type='button';button.textContent='Load setup';button.addEventListener('click',()=>{try{loadSettings(run.setup);message('Starting setup restored.');}catch{message('This saved setup could not be restored.');}});row.append(description,button);host.append(row);}}
$('#depth-mode').addEventListener('change',()=>{autoDepth=null;lastDepthPick=-Infinity;labels();});
for(const id of ['speed','radius','strength','depth','recovery','zoom','size'])$('#'+id).addEventListener('input',labels);$('#shape').addEventListener('change',()=>reset('formation'));$('#moving').addEventListener('change',labels);$('#apply-count').addEventListener('click',()=>reset('particle count'));$('#count').addEventListener('keydown',e=>{if(e.key==='Enter')reset('particle count');});$('#seed').addEventListener('change',()=>reset('seed'));$('#pause').addEventListener('click',()=>setPaused(!paused));$('#reset').addEventListener('click',()=>reset());$('#home-camera').addEventListener('click',()=>{yaw=.48;pitch=.3;pan=[0,0];$('#zoom').value=100;labels();});$('#backend').addEventListener('change',()=>initEngine($('#backend').value==='cpu'));
for(const b of document.querySelectorAll('[data-tool]'))b.addEventListener('click',()=>{tool=b.dataset.tool;held=false;dragging=false;document.querySelectorAll('[data-tool]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));canvas.style.cursor=tool==='push'?'crosshair':tool==='pan'?'move':'grab';$('#interaction-hint').textContent=tool==='push'?'Hold and drag to push · Scroll to zoom':tool==='orbit'?'Drag to orbit · Scroll to zoom':'Drag to pan · Scroll to zoom';});
$('#save-setup').addEventListener('click',()=>download('particle-setup-'+stamp()+'.json',JSON.stringify(settings(),null,2),'application/json'));$('#load-setup').addEventListener('click',()=>$('#import-file').click());$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20000)throw Error('Setup file is too large');loadSettings(JSON.parse(await file.text()));message('Setup loaded.');}catch(err){message(err.message);}e.target.value='';});
$('#screenshot').addEventListener('click',()=>{const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const c=out.getContext('2d');c.drawImage(canvas,0,0);c.drawImage(overlay,0,0);out.toBlob(blob=>{if(blob)download('particle-scene-'+stamp()+'.png',blob,'image/png');});});$('#export-csv').addEventListener('click',()=>{if(!samples.length)return message('Wait for a few timing samples first.');const keys=Object.keys(samples[0]);const text=[keys.join(','),...samples.map(s=>keys.map(k=>s[k]===null?'':String(s[k])).join(','))].join('\n');download('particle-timings-'+stamp()+'.csv',text,'text/csv');});
$('#record-run').addEventListener('click',()=>{if(!samples.length)return message('Wait for measured timings first.');const recent=samples.slice(-30);history.unshift({setup:settings(),date:new Date().toLocaleString(),mode:engine.label,fps:recent.reduce((a,s)=>a+s.fps,0)/recent.length});history=history.slice(0,12);saveLocal('particle-lab-history',history);drawHistory();message('Snapshot recorded below.');});$('#restore-layout').addEventListener('click',()=>{root.style.removeProperty('--side');root.style.removeProperty('--view');try{localStorage.removeItem('particle-lab-layout');}catch{};});for(const id of ['show-frame','show-submit','show-gpu'])$('#'+id).addEventListener('change',drawChart);
$('#ai-enabled').addEventListener('change',()=>{if(!$('#ai-enabled').checked){$('#live-error').textContent='Comparison off';$('#prediction-time').textContent='—';latestError=null;}else lastCompare=0;});document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','BUTTON','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();setPaused(!paused);}if(e.key==='Escape'){held=false;dragging=false;mouse.inside=false;}});document.addEventListener('visibilitychange',()=>{last=performance.now();accum=0;held=false;dragging=false;});window.addEventListener('blur',()=>{held=false;dragging=false;});
history=readLocal('particle-lab-history',[]);if(!Array.isArray(history))history=[];history=history.filter(r=>r&&r.setup&&Number.isInteger(r.setup.shape)&&r.setup.shape>=0&&r.setup.shape<4&&Number.isFinite(r.setup.count)&&Number.isFinite(r.fps)).slice(0,12);bindDividers();initEngine(new URLSearchParams(location.search).get('cpu')==='1');new ResizeObserver(()=>{engine.resize();drawChart();}).observe($('#viewport'));new ResizeObserver(drawChart).observe($('#chart-wrap'));drawHistory();loadModel();requestAnimationFrame(frame);
// Read-only diagnostic access for reproducible local verification.
window.particleLab={get engine(){return engine;},get phase(){return phase;},get samples(){return samples.slice();},get model(){return model;},params,settings,loadSettings,reset,get paused(){return paused;}};
